# Generated by Django 3.1.3 on 2020-11-08 06:56

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201108_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default=posts.models.callback, max_length=100),
        ),
    ]
