# Generated by Django 3.1.3 on 2020-11-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201124_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_pdf',
            field=models.FileField(default='', null=True, upload_to='pdf'),
        ),
    ]
