# Generated by Django 3.1.3 on 2020-11-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201125_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, default='/img/me.jpg', null=True, upload_to='img'),
        ),
    ]
