# Generated by Django 3.1.3 on 2020-11-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201125_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_pdf',
            field=models.FileField(blank=True, default='', null=True, upload_to='pdf'),
        ),
    ]
