# Generated by Django 3.0.5 on 2020-12-27 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_pingbacks',
        ),
    ]
